### ISSUE TITLE
Mockups Fuentes de Financiamiento 

### ISSUE THREAD

**Issue by CarlosGutierrezArdila** [davidmm07/financiera_cliente_new#24]
Creación de los mockups de procesos de fuentes de financiamiento, creación
- 5 horas - Carlos 
- [x] Diseño de los mockups en la herramienta draw.io
- [x] Incluir el mockup en el repositorio de documentación del proyecto

**Comment by CarlosGutierrezArdila** [comment]
Se dejan los mockups de registro de fuentes de financiamiento en el apartado correspondiente del [Repositorio de documentación](https://github.com/udistrital/Financiera_documentacion/blob/master/plan_cuentas/fuentes_financiamiento/mockups.md) y se incluyen las pestañas correspondientes en el [Archivo de diseño de mockups](https://drive.google.com/file/d/1nBwIdN-Iue5I164bOOjwuNPBYWJMcBPB/view?usp=sharing)

**Comment by Soulfilip-UD** [comment]
Siguiente Tarea socializar los mockups, se aduntan para la siguiente reunión con el cliente.
Proceeding t close Issue :space_invader:
