### ISSUE TITLE
Cliente de vinculación de Fuentes de financiamiento con rubros y dependencias

### ISSUE THREAD

**Issue by juancsr** [davidmm07/financiera_cliente_new#27]
- [x] Validar los mockups del cliente
- [x] Crear los componentes para el formulario de registro

**Comment by juancsr** [comment]
Tarea tomada por @macaguegi y @CarlosGutierrezArdila

**Comment by juancsr** [comment]
Al validar el mockup con el usuario, se determino que debe existir un paso antes de asignar los rubros y las dependencias a la fuente de financiamiento. Por tanto, esta tarea hace referencia sólo al formulario de asociar fuentes de financiamiento con rubros y dependencias.

**Comment by Soulfilip-UD** [comment]
Tarea realizada , tardo en cerrarse

Proceeding to close Issue 👾
