### ISSUE TITLE
Integración de cliente en registro de fuentes - 8 horas - Juan Camilo

### ISSUE THREAD

**Issue by juancsr** [davidmm07/financiera_cliente_new#31]
Integrar los servicios para registrar fuentes en el cliente De Fuentes de financiamiento

**Comment by juancsr** [comment]
Debido a que se agregaron los productos a la vinculación de fuentes de financiamiento, deben redefinirse los modelos de datos y ajustarse en los servicios de registro

**Comment by Soulfilip-UD** [comment]
Se cierrar el Issue por el momento, se reabre cuando se vuelva a trabajar en el desarrollo de fuentes
