### ISSUE TITLE
Parametrizar textos de los labels en el cliente

### ISSUE THREAD

**Issue by CarlosGutierrezArdila** [davidmm07/financiera_cliente_new#32]
- [x] Revisar la estructura del servicio de traducción en la plantilla
- [x] Actualizar el diccionario de etiquetas en el archivo de configuración para los componentes existentes
- [x] Corregir en los componentes existentes los labels que están escritos directamente y traerlos del servicio

**Comment by CarlosGutierrezArdila** [comment]
Para usar el servicio de traducción en los módulos es necesario importar el modulo shared:
![image](https://user-images.githubusercontent.com/32855979/60841097-947e9200-a196-11e9-8d57-02639b88de75.png)
luego se definen los labels a utilizar en el archivo assets/es.json que es el archivo que se va a utilizar como parametro:
![image](https://user-images.githubusercontent.com/32855979/60841203-d7406a00-a196-11e9-92fb-e3ca5cee769b.png)
Luego, en el componente se debe importar el servicio de traduccion e instanciarlo:
![image](https://user-images.githubusercontent.com/32855979/60841247-f808bf80-a196-11e9-8650-9d790887458b.png)
```typescript
  constructor(private translate: TranslateService,) {
    this.translate.onLangChange.subscribe((event: LangChangeEvent) => {
    });
   }
  useLanguage(language: string) {
    this.translate.use(language);
  }
```
luego se llama desde el componente HTML usando el data binding de angular para evitar dejarlos explicitos:
```html
 <h1>{{'GLOBAL.gestion-titulo' | translate }} {{selectedOption.option}}</h1>
```

**Comment by Soulfilip-UD** [comment]
Muy buena Documentación y buena práctica que ha sido adoptada en nuevos desarrollos

Proceeding to close Issue 👾
