### ISSUE TITLE
Desarrollo cliente de angular 7 de Procesos de Modificaciones Presupuestales fuentes. Basado en los mockups 

### ISSUE THREAD

**Issue by CarlosGutierrezArdila** [davidmm07/financiera_cliente_new#40]
- [x] Implementar cliente reducción fuente
- [x] Implementar cliente adición fuente
- [x] Implementar cliente traslado fuente
- [ ] Implementar cliente anulación/suspension fuente

**Comment by mcguegi** [comment]
Se prolonga esta tarea al siguiente sprint ya que no se encuentran disponibles los mockups de modificaciones presupuestales.

**Comment by mcguegi** [comment]
Se da por terminada esta tarea. Queda pendiente realizar el componente para la Suspensión de una Fuente de Financiamiento ya que se está esperando retroalimentación sobre este proceso.

**Comment by Soulfilip-UD** [comment]
Se desarrolla las modificaciones en fuentes, falta por resolver anulación, pero está se solucionara en un nuevo Issue

Proceeding to close Issue 👾
