### ISSUE TITLE
Modificación mockups fuentes de acuerdo a reunion con analista 10/07/2019

### ISSUE THREAD

**Issue by CarlosGutierrezArdila** [davidmm07/financiera_cliente_new#42]
- [x] diseño consulta fuentes
- [x] diseño creación fuentes
- [x] diseño asignación de fuentes

**Comment by CarlosGutierrezArdila** [comment]
se añaden los correspondientes diseños al [documento](https://drive.google.com/file/d/1nBwIdN-Iue5I164bOOjwuNPBYWJMcBPB/view?usp=sharing) a espera de nueva socializacion con equipo y analista

**Comment by Soulfilip-UD** [comment]
Modificaciones Realizadas

Proceeding to close Issue 👾
