### ISSUE TITLE
Corregir errores de despliegue cliente

### ISSUE THREAD

**Issue by davidmm07** [davidmm07/financiera_cliente_new#45]
- [x] Validar y corregir errores con los componentes para visualizar los ultimos cambios

**Comment by davidmm07** [comment]
En jenkins en la linea del shell del build 
```sh
npm run build:prod
```
se cambia a

```sh
npm run build:dev
```

PR referenciado #46

**Comment by Soulfilip-UD** [comment]
En caso de que el lineamiento sea seguir construyendo para producción se re-abrira el Issue .
Gracias

Proceeding to close Issue 👾
