### ISSUE TITLE
Cliente -Ajustar lógica desde el cliente : solo se puede asignar apropiaciones al ultimo rubro hijo

### ISSUE THREAD

**Issue by CarlosGutierrezArdila** [davidmm07/financiera_cliente_new#49]
- [x] ajustes apropiaciones
- [x] ajustes componente arbol
- 8 horas- Carlos

**Comment by mcguegi** [comment]
Se da por terminada esta tarea y se solicita revisión de líder técnico @Soulfilip-UD . Gracias

**Comment by Soulfilip-UD** [comment]
Cambios revisados, buen trabajo!

Proceeding to close Issue :space_invader:
