### ISSUE TITLE
Consumir del endpoint arbol apropiaciones

### ISSUE THREAD

**Issue by mcguegi** [davidmm07/financiera_cliente_new#51]
Se solicita 

- [x] consumir endpoint del servicio de MONGO CRUD para visualizar el árbol de apropiaciones

**Comment by mcguegi** [comment]
Ya se está consumiendo el endpoint para cargar el árbol de apropiaciones de Mongo, sin embargo , queda pendiente hacer la carga dinámica de la interface del mismo. Este pendiente se trabajará en el issue #33.

**Comment by mcguegi** [comment]
Se adjunta documentación del helper donde se consume el endpoint para cargar el árbol de apropiaciones.

```typescript
public getFullArbol() {
        this.rqManager.setPath('PLAN_CUENTAS_MONGO_SERVICE');
        // Set the optional branch for the API request.
        const unidadEjecutora = 1;
        // call request manager for the tree's data.
        return this.rqManager.get(`arbol_rubro_apropiaciones/FullArbolRubroApropiaciones/${unidadEjecutora.toString()}`);
    }
```

**Comment by mcguegi** [comment]
Se da por terminada esta tarea y se solicita a líder técnico @Soulfilip-UD la revisión de la misma. 
:heavy_check_mark:

**Comment by Soulfilip-UD** [comment]
Tarea realziada y revisada, teemos Arbol!

Proceeding to close Issue :space_invader:
