### ISSUE TITLE
Cliente- Comparar valores de ingresos y egresos en apropiaciones

### ISSUE THREAD

**Issue by CarlosGutierrezArdila** [davidmm07/financiera_cliente_new#52]
- [x] componente comprobación 
- [x] consumo servicios saldo total

**Comment by mcguegi** [comment]
Se da por terminada esta tarea y se solicita revisión de líder técnico @Soulfilip-UD . Gracias

**Comment by Soulfilip-UD** [comment]
:+1: Genial!  Tarea realizada 

Proceeding to close Issue :space_invader:
