### ISSUE TITLE
Cliente Angular 7 - Productos - Asignacion en rubros 

### ISSUE THREAD

**Issue by CarlosGutierrezArdila** [davidmm07/financiera_cliente_new#63]
- [x] incluir componente de asignación de productos y porcentajes en rubros
- [x] Integración con componentes de productos relacionados

**Comment by CarlosGutierrezArdila** [comment]
tarea finalizada y visible en 254 pendiente integración con servicios

**Comment by Soulfilip-UD** [comment]
Tarea Realizada, la integración con los servicios se realiza en un nuevo Issue 

Proceeding to close Issue 👾
