### ISSUE TITLE
Tabla crud Productos (consulta,edicion, registro) 

### ISSUE THREAD

**Issue by mcguegi** [davidmm07/financiera_cliente_new#64]
Se solicita : 

- [x] Crear un tab para la gestión de Productos

- [x] Crear una tabla para el CRUD de Productos

**Comment by mcguegi** [comment]
Se da por terminada esta tarea y se solicita revisión de líder técnico @Soulfilip-UD  .


:smiley:

**Comment by Soulfilip-UD** [comment]
Perfecto

Proceeding to close Issue 👾
