### ISSUE TITLE
Integrar servicios de pre-asignacion apropiacion inicial

### ISSUE THREAD

**Issue by mcguegi** [davidmm07/financiera_cliente_new#70]
Se solicita integrar los nuevos endpoints del servicio de mongo para la preasignación de apropiaciones iniciales

- [x] Implementar preasignación de apropiación inicial

**Comment by mcguegi** [comment]
Se usa el endpoint /arbol_rubro_apropiacion/ y se registra la preasignación con la información y el estado "preasignado" . Sin embargo, queda pendiente revisar la actualización de la apropiación inicial y la preasignación a rubros que no tienen apropiación inicial . Se solicita revisión de líder técnico @Soulfilip-UD

**Comment by mcguegi** [comment]
Se solicita cierre de esta tarea.  Ya que los servicios de preasignación se actualizaron en el cliente.

**Comment by Soulfilip-UD** [comment]
entendido !

Proceeding to close Issue 👾
