### ISSUE TITLE
Integrar servicios de consulta e inserción de rubros presupuestales

### ISSUE THREAD

**Issue by mcguegi** [davidmm07/financiera_cliente_new#71]
Se solicita modificar los servicios de rubros en el cliente para ajustarlos al nuevo servicio de Mongo. 

- [x] Realizar consulta de Rubros

- [x] Realizar registro de Rubros

**Comment by mcguegi** [comment]
La consulta de Rubros es la visualización del árbol de rubros :evergreen_tree: . Sin embargo, se encuentran problemas en la estructura del servicio y por lo tanto no se está desplegando correctamente el árbol de rubros. A diferencia del árbol de apropiaciones que se visualiza de la siguiente manera : 

![image](https://user-images.githubusercontent.com/12780939/62011961-3f0a2500-b145-11e9-89fb-056f870be9e3.png)

Se deja a consideración de líder técnico @Soulfilip-UD la terminación de esta tarea dado que al parecer esta depende de ajustes en el servicio de mongo.

**Comment by mcguegi** [comment]
Con ayuda del desarrollador @davidmm07 se cargan perfectamente los árboles de rubros y apropiaciones . Se solicita revisión de líder técnico @Soulfilip-UD

**Comment by Soulfilip-UD** [comment]
Tarea revisada y está finalizada
Gracias a @davidmm07 !

Proceeding to close Issue 👾
