### ISSUE TITLE
Cliente Angular 7 - Productos - Asignacion en Fuentes

### ISSUE THREAD

**Issue by davidmm07** [davidmm07/financiera_cliente_new#77]
- [x] Generar Vista de asignación de fuentes
- [x] Integrar con los endpoint requeridos del api mongo.

**Comment by davidmm07** [comment]
Se Toma en cuenta la estructura de productos en las fuentes para el endpoint /fuente_financiamiento
```
{
	"Vigencia": 2019,
	"Nombre": "fuente de financiamiento 1",
	"Descripcion": "descripcion de la fuente de financiamiento 1",
	"FechaCreacion": "2018-09-01T05:00:00.000Z",
	"FechaModificacion": "2018-09-01T05:00:00.000Z",
	"Activo": true,
	"TipoFuente": "algo del tipo de fuente",
	"ValorOriginal": 30000,
	"ValorAcumulado": 0,
	"Codigo": "fuente3",
	"Rubros": {
		"3-1": {
			"Productos": [1,2,3],
			"Dependencias": [
				{
					"Id": 30,
					"ValorDependencia": 300
				},
				{
					"Id": 31,
					"ValorDependencia": 450
				}
			]
		},
		"3-2": {
			"Productos": [4,5,6],
			"Dependencias": [
				{
					"Id": 35,
					"ValorDependencia": 500
				}
			]
		}
	}
}
```

**Comment by Soulfilip-UD** [comment]
Para finalizar está tarea se reuiere haber finalizado los dos siguientes Issues :

- [x] https://github.com/udistrital/presupuesto_cliente/issues/69

- [x] https://github.com/udistrital/presupuesto_cliente/issues/79

Actualmente se està trabajando en està

**Comment by davidmm07** [comment]
Se solicita revisión de líder @Soulfilip-UD, tarea terminada

**Comment by Soulfilip-UD** [comment]
La tarea se finaliza correctamente

Proceeding to close Issue :space_invader:
