### ISSUE TITLE
Asignar dependecias y validar los valores de las mismas en fuentes 

### ISSUE THREAD

**Issue by davidmm07** [davidmm07/financiera_cliente_new#79]
- [x] Generar proceso que asigne las dependencias y valide los valores correspondientes al de la fuente.

**Comment by davidmm07** [comment]
Se solicita revisión de líder @Soulfilip-UD, tarea terminada

**Comment by Soulfilip-UD** [comment]
Se estàn validando correctamente las apropiaciones

Proceeding to close issue :space_invader:
