### ISSUE TITLE
Integrar servicios de productos con Tabla CRUD Productos

### ISSUE THREAD

**Issue by mcguegi** [davidmm07/financiera_cliente_new#82]
Se solicita integrar los servicios de mongo para productos con el fin de : 

- [x] Consultar Productos

- [x] Crear Productos

- [x] Editar Productos

- [x] Borrar Productos

**Comment by mcguegi** [comment]
Se da por terminada esta tarea y se solicita revisión de líder técnico @Soulfilip-UD .

**Comment by Soulfilip-UD** [comment]
Listo tarea revisada  y finalizada

Proceeding to close Issue 👾
