### ISSUE TITLE
Edición del rubro - Hace falta el campo de unidad ejecutora , Hace falta el boton para poder editar el detalle del rubro y que los campos se habiliten para edición

### ISSUE THREAD

**Issue by CarlosGutierrezArdila** [davidmm07/financiera_cliente_new#83]
- [x] Visualizar campo unidad ejecutora
- [x] Flujo de editar rubro seleccionado
- [x] Funcionalidad PUT rubro
 - 5 horas - Carlos

**Comment by CarlosGutierrezArdila** [comment]
Se deja tarea para revision de lider tecnico @Soulfilip-UD

**Comment by Soulfilip-UD** [comment]
Listo tarea revisada y finalizada 


Proceeding to close Issue 👾
