### ISSUE TITLE
Creación de rubro y  Validación del campo de vigencia 

### ISSUE THREAD

**Issue by mcguegi** [davidmm07/financiera_cliente_new#84]
Hacer el POST de rubro y tener en cuenta que la Vigencia no hace parte de la creacion de un rubro hijo, quitar requerido 

- [x] Visualización árbol

- [x] Quitar vigencia del formulario

- [x] POST Rubro

**Comment by mcguegi** [comment]
Se da por terminada esta tarea ya que se puede visualizar el árbol y hacer el registro de rubros en ambiente local. Se solicita revisión de líder técnico @Soulfilip-UD .

**Comment by Soulfilip-UD** [comment]
Listo revisada
Tarea Finalizada

Proceeding to close Issue 👾
