### ISSUE TITLE
**cliente** Asignación de productos a rubros - Agregar boton de asignar productos al rubro e Integrar a los servicios del backend - 5 horas - Miguel

### ISSUE THREAD

**Issue by miguelramirez93** [davidmm07/financiera_cliente_new#94]
- [ ] integrar servicios API para consulta de productos
- [ ] generar funciones para registro de Productos a un rubro

**Comment by miguelramirez93** [comment]
Se congela la tarea por error en despliegues. Se deja pendiente hasta nueva orden

**Comment by miguelramirez93** [comment]
Se congela la tarea por error en despliegues. Se deja pendiente hasta nueva orden

**Comment by Soulfilip-UD** [comment]
El desarrollo se detiene , concentrarse en la migración

**Comment by Soulfilip-UD** [comment]
La tarea esta duplicada y se soluciono en el repositorio de (presupuesto_cliente_angular_8) y se procede a cerrar el Issue

Proceeding to close Issue 👾
