### ISSUE TITLE
**cliente. mongo**  Apropiación Inicial - Componente de validación de egresos vs ingresos - integrar al servicio de back , ya que trabaja con datos estaticos y la comprobación la deberia realizar desde el back  -- Miguel

### ISSUE THREAD

**Issue by miguelramirez93** [davidmm07/financiera_cliente_new#95]
- [ ] Integrar servicios back
- [ ] Generar funciones para validación de apr inicial

**Comment by Soulfilip-UD** [comment]
La tarea esta duplicada y se soluciono en el repositorio de (presupuesto_cliente_angular_8) y se procede a cerrar el Issue 

Proceeding to close Issue 👾
